#!/bin/sh

mysql_ready() {
    mysqladmin ping -h 127.0.0.1 -uping -pping > /dev/null 2>&1
}

run_mysql() {
    /usr/bin/mysqld --user=root --skip-name-resolve --skip-networking=0 &
}

while !(mysql_ready)
do
    mysql_ready
    if [ $? -ne 0 ]; then
        run_mysql
    fi
    sleep 3s
done

# Just For Old Version, should be do this in Dockerfile
if [[ -f /var/www/html/db.sql ]]; then
    echo "[+] Init db.sql"
    mysql -uroot -proot -e "source /var/www/html/db.sql"
    rm -f /var/www/html/db.sql
fi

if [[ -f /flag.sh ]]; then
    echo "[+] Init flag.sh"
    source /flag.sh
fi

while true
do
    mysql_ready
    if [ $? -ne 0 ]; then
        run_mysql
    fi
    ps -e | grep 'php-fpm' | grep -v grep > /dev/null
    if [ $? -ne 0 ]; then
        php-fpm &
    fi
    ps -e | grep 'nginx:' | grep -v grep > /dev/null
    if [ $? -ne 0 ]; then
        nginx &
    fi
    sleep 5s
done
