FROM registry.cn-hangzhou.aliyuncs.com/lxepoo/apache-php5


RUN rm -rf /var/www/*
ADD ./www /var/www/
RUN rm -rf /usr/local/etc/php/conf.d/php.ini
ADD ./php.ini /usr/local/etc/php/conf.d/
RUN chown -R www-data:www-data /var/www/
RUN echo SYC{welc0me_t0_up10ad_wor1d!} > /flag

